### ISSUE TITLE
interrupts

### ISSUE THREAD

**Issue by Vorms** [LennartHennigs/ESPRotary#27]
Hello,
Nice jobs, but why this library is not interrupt driven ?

Best regards
Thierry

**Comment by LennartHennigs** [comment]
Hello,
thanks. 
Well, because I designed it differently?  ^^
You could of course replace the loop function with interrupts listeners but I thought this was an easier and more universal approach. Now you don't need to know or lookup which pins can handle interrupts. You just have to use the loop function.

Cheers
l.

**Comment by BCsabaEngine** [comment]
And not so easy handle multiple rotary with interrupts.
